#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gnome-terminal desktop='^1' follow=on
bspc rule -a Alacritty  state=floating follow=on
bspc rule -a Gimp desktop='^9' state=floating follow=on
bspc rule -a Inkscape desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^5' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a code desktop='^3' follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a nm-connection-editor state=floating
bspc rule -a Screenkey manage=off

feh --bg-fill /home/johnaiker/Images/Wallpapers/lofi-experience-2-voyager-2-1600×900.jpg &

~/.config/polybar/./launch2.sh --cuts &

picom &

nm-applet &  
